**Name** : Rupali Arun Kondke
**Class** : SY-A
**Branch **: AI & DS
**Roll NO** : A-57

#            PRACTICAL NO.2

**AIM** : Data Ingestion and Cleaning: Acquire data and prepare it for analysis.

**1. What is data ingestion and why is it important in data science? Which Python library is commonly used for data ingestion and cleaning**?

**ANS** :
Data ingestion is the process of importing and transferring data from various sources into a storage system or a database where it can be accessed, processed, and analyzed. This can include data from databases, files, APIs, streaming sources, and more.

**Importance in Data Science**:

1.  **Foundation for Analysis**: Without proper data ingestion, there is no data to analyze. It's the critical first step in any data science project.
2.  **Data Quality**: It allows for the initial cleaning and validation of data, ensuring that the data used for analysis is accurate and reliable.
3.  **Data Accessibility**: It centralizes data from disparate sources, making it easier for data scientists to access and work with a unified dataset.
4.  **Scalability**: Effective ingestion strategies enable handling large volumes of data, which is crucial for big data applications.
5.  **Timeliness**: For real-time analytics, efficient data ingestion ensures that the data is available for processing as soon as it's generated.

**Common Python Library for Data Ingestion and Cleaning**:

**Pandas** is by far the most commonly used Python library for data ingestion and cleaning. It provides powerful and flexible data structures (like DataFrames) and functions that make it easy to:

*   **Ingest Data**: Read data from various formats such as CSV, Excel, SQL databases, JSON, HTML, Parquet, and more.
*   **Clean Data**: Handle missing values (e.g., `fillna()`, `dropna()`), remove duplicates (`drop_duplicates()`), correct data types (`astype()`), rename columns (`rename()`), and transform data (`apply()`, `map()`).
*   **Manipulate Data**: Filter, sort, group, merge, and reshape data efficiently.

**2. Why is data cleaning necessary before performing analysis or machine learning**?

**ANS** :
Data cleaning is a crucial step before performing analysis or machine learning for several key reasons:

1.  **Ensures Data Quality and Accuracy**: Raw data often contains errors, inconsistencies, and inaccuracies. These can include typos, incorrect values, out-of-range data, or data entry mistakes. Cleaning helps correct these issues, ensuring that the data reflects reality as closely as possible.

2.  **Improves Model Performance**: Machine learning models are highly sensitive to the quality of the input data. Dirty data can lead to:
    *   **Inaccurate Predictions**: Models trained on flawed data will produce unreliable and incorrect predictions.
    *   **Reduced Performance**: Noise and inconsistencies can prevent models from learning the true underlying patterns in the data, leading to lower accuracy, precision, recall, or F1-scores.
    *   **Bias**: If errors are systematic (e.g., specific groups of data are consistently misrepresented), the model can learn and perpetuate these biases.

3.  **Handles Missing Values**: Missing data is common and can be problematic. Cleaning involves strategies to address missing values, such as imputation (filling in missing values based on other data) or removal of records/features. Ignoring missing values can lead to biased results or algorithms failing to run.

4.  **Removes Duplicates**: Duplicate records can skew analysis, inflate statistics, and lead to overfitting in machine learning models by giving undue weight to certain observations. Data cleaning identifies and removes these redundant entries.

5.  **Corrects Inconsistent Formatting and Data Types**: Data from multiple sources might have different formats for the same information (e.g., 'USA', 'U.S.', 'United States' for a country, or dates in 'MM/DD/YYYY' vs. 'YYYY-MM-DD'). Inconsistent data types (e.g., numbers stored as strings) can also prevent proper calculations or model training. Cleaning standardizes these aspects.

6.  **Identifies and Addresses Outliers**: Outliers are data points that significantly differ from other observations. While some outliers might represent valid, extreme cases, others can be errors. Cleaning helps identify them and decide whether to remove, transform, or keep them based on domain knowledge, as they can heavily influence statistical analyses and model training.

7.  **Enhances Interpretability and Insights**: Clean data is easier to understand and interpret. When data is clean, analysts can be more confident in the insights derived from it, making conclusions more robust and actionable.

8.  **Reduces Computation Time and Resources**: Working with clean, well-structured data often requires less computational power and time for processing and analysis, as algorithms don't have to contend with erroneous entries or inconsistencies.

In essence, data cleaning transforms raw, imperfect data into a reliable and usable format, forming the bedrock for sound data analysis, robust machine learning models, and credible insights.

**3. How do you load a CSV file into a Pandas DataFrame**?

**ANS** :
To load a CSV (Comma Separated Values) file into a Pandas DataFrame, you typically follow these steps:

1.  **Import the Pandas Library**: You need to import the pandas library, usually aliased as `pd`, at the beginning of your script or notebook.
2.  **Use `pd.read_csv()` Function**: Pandas provides the `read_csv()` function specifically for this purpose. You pass the path to your CSV file as the first argument.

**Explanation:**
*   You first need to import the `pandas` library, which is a powerful data manipulation tool in Python, usually by writing `import pandas as pd`.
*   Once imported, you use the `read_csv()` function from the pandas library. This function is designed to ingest data from CSV files.
*   You provide the file path of your CSV file as an argument to `pd.read_csv()`. For example, `df = pd.read_csv('path/to/your/file.csv')`.
*   The `read_csv()` function then parses the CSV file, interpreting each row as a record and splitting columns based on commas (or other specified delimiters), and organizes this data into a two-dimensional tabular structure called a DataFrame.
*   The result is a Pandas DataFrame object, which you can store in a variable (e.g., `df`) for further analysis and manipulation. It's often good practice to display the first few rows of the DataFrame (e.g., using `df.head()`) to quickly verify that the data has been loaded correctly.

 4. **What is the difference between head() and tail() functions in Pandas**?

** ANS **:
In Pandas, both `head()` and `tail()` are DataFrame methods used for quickly inspecting parts of a DataFrame, but they serve opposite purposes:

*   **`head(n=5)`**: This method returns the **first `n` rows** of the DataFrame. By default, if `n` is not specified, it returns the first 5 rows. It's incredibly useful for getting a quick glimpse of the data's structure, column names, and initial values to ensure that the data has been loaded or processed correctly.

*   **`tail(n=5)`**: This method returns the **last `n` rows** of the DataFrame. Similar to `head()`, if `n` is not specified, it returns the last 5 rows. `tail()` is useful for checking the end of a DataFrame, which can be particularly helpful for time-series data to see the latest entries or to confirm that data was appended correctly.

5. **How can you identify missing values in a dataset?**

**ANS** :
Identifying missing values is a crucial part of data cleaning. In Python, especially with the Pandas library, there are several effective ways to do this:

1.  **Using `df.isnull()` or `df.isna()`**: These methods return a boolean DataFrame of the same shape as the original, indicating `True` for missing values (NaN, None, NaT) and `False` otherwise. `isnull()` and `isna()` are aliases for each other and can be used interchangeably.

    *   **To check for missing values across the entire DataFrame:**
        ```python
        df.isnull()
        ```

    *   **To get a count of missing values per column:**
        ```python
        df.isnull().sum()
        ```
        This is a very common and useful approach. It sums the `True` values (which are treated as 1) for each column.

    *   **To get the total number of missing values in the entire DataFrame:**
        ```python
        df.isnull().sum().sum()
        ```

    *   **To get the percentage of missing values per column:**
        ```python
        df.isnull().sum() / len(df) * 100
        ```

2.  **Using `df.info()`**: This method prints a concise summary of a DataFrame, including the data types of columns and the number of non-null values. By comparing the 'Non-Null Count' with the 'Entries' (total number of rows), you can quickly see which columns have missing values.

    ```python
    df.info()
    ```

3.  **Using `df.describe()` (for numerical data)**: While primarily for descriptive statistics, if a numerical column has missing values, its count will be less than the total number of rows. This can indirectly point to missing data, though `isnull().sum()` is more direct.

    ```python
    df.describe()
    ```

4.  **Visualizing Missing Data**: For a more intuitive understanding, especially with many columns, visualization libraries can be used:

    *   **Missingno Library**: This is a popular library specifically designed for visualizing missing data patterns. It offers matrix, bar, heatmap, and dendrogram plots.

        ```python
        # import missingno as msno
        # msno.matrix(df)
        # msno.bar(df)
        ```

By using these methods, you can effectively identify the presence, location, and extent of missing values in your dataset, which is the first step towards handling them appropriately.

**CONCLUSION **:

The program successfully achieved the aim of 'Data Ingestion and Cleaning: Acquire data and prepare it for analysis.' Through a series of well-defined steps, including loading a synthetic CSV dataset, identifying and handling missing values (via zero-filling and mean/median imputation), removing duplicate entries, standardizing column names, converting data types, and filtering data based on conditions, the program effectively demonstrated fundamental data preparation techniques. The final cleaned dataset, saved to a new CSV file, represents a well-structured and refined version of the initial raw data, ready for further analysis or machine learning tasks. This practical successfully illustrated the importance of cleaning and preparing data to ensure its quality and suitability for subsequent data science processes.

### Data Ingestion and Cleaning Program

This program demonstrates various data ingestion and cleaning techniques using a single synthetic dataset. It covers tasks for both 'Weak' (Basic) and 'Normal' (Moderate) students as per your requirements.

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np

# 0. Generate a Synthetic Dataset
# This dataset will have missing values, duplicate rows, and mixed data types
data = {
    'ProductID': [1, 2, 3, 4, 5, 1, 6, 7, 8, 9],
    'ProductName': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam', 'Laptop', 'Speaker', 'Headphones', 'Microphone', 'Router'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Audio', 'Audio', 'Audio', 'Network'],
    'Price': [1200.00, 25.50, 75.00, 300.00, np.nan, 1200.00, 80.00, 50.00, 60.00, np.nan],
    'StockQuantity': [10, 50, 30, 15, 20, 10, np.nan, 40, 25, 12],
    'Rating': [4.5, 3.8, 4.2, 4.0, 3.5, 4.5, 4.1, 4.3, 3.9, 4.0],
    'ReleaseDate': ['2023-01-15', '2023-02-01', '2022-11-20', '2023-03-10', '2023-01-05', '2023-01-15', '2022-10-01', '2023-04-20', '2023-03-25', '2022-12-12']
}
df_synthetic = pd.DataFrame(data)

# Introduce some string inconsistencies and more missing values for demonstration
df_synthetic.loc[4, 'Category'] = 'electronics' # Inconsistent case
df_synthetic.loc[7, 'ProductName'] = 'Headphones ' # Trailing space
df_synthetic.loc[2, 'Price'] = 75.50
df_synthetic.loc[8, 'Rating'] = np.nan # Another missing rating

# Save the synthetic dataset to a CSV file
csv_file_path = 'synthetic_products.csv'
df_synthetic.to_csv(csv_file_path, index=False)

print(f"Synthetic dataset created and saved to '{csv_file_path}'")
print("Original synthetic data head:")
display(df_synthetic.head())

Synthetic dataset created and saved to 'synthetic_products.csv'
Original synthetic data head:

,ProductID,ProductName,Category,Price,StockQuantity,Rating,ReleaseDate
0,1,Laptop,Electronics,1200.0,10.0,4.5,2023-01-15
1,2,Mouse,Electronics,25.5,50.0,3.8,2023-02-01
2,3,Keyboard,Electronics,75.5,30.0,4.2,2022-11-20
3,4,Monitor,Electronics,300.0,15.0,4.0,2023-03-10
4,5,Webcam,electronics,NaN,20.0,3.5,2023-01-05

---

In [ ]:
# 1. Load a CSV file using pandas and display first five rows.
print(f"Loading data from '{csv_file_path}'...")
df = pd.read_csv(csv_file_path)
print("First 5 rows of the loaded dataset:")
display(df.head())

Loading data from 'synthetic_products.csv'...
First 5 rows of the loaded dataset:

,ProductID,ProductName,Category,Price,StockQuantity,Rating,ReleaseDate
0,1,Laptop,Electronics,1200.0,10.0,4.5,2023-01-15
1,2,Mouse,Electronics,25.5,50.0,3.8,2023-02-01
2,3,Keyboard,Electronics,75.5,30.0,4.2,2022-11-20
3,4,Monitor,Electronics,300.0,15.0,4.0,2023-03-10
4,5,Webcam,electronics,NaN,20.0,3.5,2023-01-05

In [ ]:
# 2. Identify missing values in a dataset.
print("Missing values before any cleaning (sum per column):")
display(df.isnull().sum())

print("Total missing values in the dataset:")
display(df.isnull().sum().sum())

Missing values before any cleaning (sum per column):

ProductID        0
ProductName      0
Category         0
Price            2
StockQuantity    1
Rating           1
ReleaseDate      0
dtype: int64

Total missing values in the dataset:

np.int64(4)

In [ ]:
# 3. Replace missing values with zero.
# We will create a copy to demonstrate this, keeping the original for other strategies
df_zero_filled = df.fillna(0)
print("DataFrame after replacing all missing values with zero (first 5 rows):")
display(df_zero_filled.head())
print("Missing values after replacing with zero (should be 0):")
display(df_zero_filled.isnull().sum())

DataFrame after replacing all missing values with zero (first 5 rows):

,ProductID,ProductName,Category,Price,StockQuantity,Rating,ReleaseDate
0,1,Laptop,Electronics,1200.0,10.0,4.5,2023-01-15
1,2,Mouse,Electronics,25.5,50.0,3.8,2023-02-01
2,3,Keyboard,Electronics,75.5,30.0,4.2,2022-11-20
3,4,Monitor,Electronics,300.0,15.0,4.0,2023-03-10
4,5,Webcam,electronics,0.0,20.0,3.5,2023-01-05

Missing values after replacing with zero (should be 0):

ProductID        0
ProductName      0
Category         0
Price            0
StockQuantity    0
Rating           0
ReleaseDate      0
dtype: int64

In [ ]:
# 4. Rename column names to lowercase.
df.columns = df.columns.str.lower()
print("Column names after converting to lowercase:")
display(df.columns)

Column names after converting to lowercase:

Index(['productid', 'productname', 'category', 'price', 'stockquantity',
       'rating', 'releasedate'],
      dtype='object')

In [ ]:
# 5. Display dataset shape (rows and columns).
print(f"Dataset shape (rows, columns): {df.shape}")

Dataset shape (rows, columns): (10, 7)

---

In [ ]:
# 6. Remove duplicate rows from a dataset.
print("Dataset shape before removing duplicates:", df.shape)
df_cleaned = df.drop_duplicates()
print("Dataset shape after removing duplicates:", df_cleaned.shape)
print("First 5 rows after removing duplicates:")
display(df_cleaned.head())

Dataset shape before removing duplicates: (10, 7)
Dataset shape after removing duplicates: (9, 7)
First 5 rows after removing duplicates:

,productid,productname,category,price,stockquantity,rating,releasedate
0,1,Laptop,Electronics,1200.0,10.0,4.5,2023-01-15
1,2,Mouse,Electronics,25.5,50.0,3.8,2023-02-01
2,3,Keyboard,Electronics,75.5,30.0,4.2,2022-11-20
3,4,Monitor,Electronics,300.0,15.0,4.0,2023-03-10
4,5,Webcam,electronics,NaN,20.0,3.5,2023-01-05

In [ ]:
# 7. Handle missing values using mean or median.
# We'll use the 'Price' and 'StockQuantity' columns for this.
# First, let's see the current missing values in df_cleaned
print("Missing values before mean/median imputation:")
display(df_cleaned.isnull().sum())

# Impute 'Price' with its mean
if 'price' in df_cleaned.columns:
    mean_price = df_cleaned['price'].mean()
    # Using .loc to avoid SettingWithCopyWarning
    df_cleaned.loc[:, 'price'] = df_cleaned['price'].fillna(mean_price)
    print(f"'Price' column missing values filled with mean: {mean_price:.2f}")

# Impute 'StockQuantity' with its median
if 'stockquantity' in df_cleaned.columns:
    median_stock = df_cleaned['stockquantity'].median()
    # Using .loc to avoid SettingWithCopyWarning
    df_cleaned.loc[:, 'stockquantity'] = df_cleaned['stockquantity'].fillna(median_stock)
    print(f"'StockQuantity' column missing values filled with median: {median_stock}")

# Impute 'Rating' with its mean as well
if 'rating' in df_cleaned.columns:
    mean_rating = df_cleaned['rating'].mean()
    # Using .loc to avoid SettingWithCopyWarning
    df_cleaned.loc[:, 'rating'] = df_cleaned['rating'].fillna(mean_rating)
    print(f"'Rating' column missing values filled with mean: {mean_rating:.2f}")

print("Missing values after mean/median imputation:")
display(df_cleaned.isnull().sum())
print("First 5 rows after mean/median imputation:")
display(df_cleaned.head())

Missing values before mean/median imputation:

productid        0
productname      0
category         0
price            0
stockquantity    0
rating           0
releasedate      0
dtype: int64

'Price' column missing values filled with mean: 255.86
'StockQuantity' column missing values filled with median: 22.5
'Rating' column missing values filled with mean: 4.05
Missing values after mean/median imputation:

productid        0
productname      0
category         0
price            0
stockquantity    0
rating           0
releasedate      0
dtype: int64

First 5 rows after mean/median imputation:

,productid,productname,category,price,stockquantity,rating,releasedate
0,1,Laptop,Electronics,1200.000000,10.0,4.5,2023-01-15
1,2,Mouse,Electronics,25.500000,50.0,3.8,2023-02-01
2,3,Keyboard,Electronics,75.500000,30.0,4.2,2022-11-20
3,4,Monitor,Electronics,300.000000,15.0,4.0,2023-03-10
4,5,Webcam,electronics,255.857143,20.0,3.5,2023-01-05

In [ ]:
# 8. Change data types of selected columns.
# Convert 'release_date' to datetime and 'productid' to string (if it were not already int)

print("Original data types:")
display(df_cleaned.dtypes)

if 'releasedate' in df_cleaned.columns:
    # Using .loc to avoid SettingWithCopyWarning
    df_cleaned.loc[:, 'releasedate'] = pd.to_datetime(df_cleaned['releasedate'])
    print("Changed 'releasedate' to datetime type.")

if 'productid' in df_cleaned.columns:
    # Using .loc to avoid SettingWithCopyWarning
    df_cleaned.loc[:, 'productid'] = df_cleaned['productid'].astype(str)
    print("Changed 'productid' to string type.")

print("New data types:")
display(df_cleaned.dtypes)
print("First 5 rows after data type conversion:")
display(df_cleaned.head())

Original data types:

productid                object
productname              object
category                 object
price                   float64
stockquantity           float64
rating                  float64
releasedate      datetime64[ns]
dtype: object

Changed 'releasedate' to datetime type.
Changed 'productid' to string type.
New data types:

productid                object
productname              object
category                 object
price                   float64
stockquantity           float64
rating                  float64
releasedate      datetime64[ns]
dtype: object

First 5 rows after data type conversion:

,productid,productname,category,price,stockquantity,rating,releasedate
0,1,Laptop,Electronics,1200.000000,10.0,4.5,2023-01-15
1,2,Mouse,Electronics,25.500000,50.0,3.8,2023-02-01
2,3,Keyboard,Electronics,75.500000,30.0,4.2,2022-11-20
3,4,Monitor,Electronics,300.000000,15.0,4.0,2023-03-10
4,5,Webcam,electronics,255.857143,20.0,3.5,2023-01-05